 
PostgreSQL:
  restart: on-failure
  image: sameersbn/postgresql:10-2
  ports:
    - "5432:5432"
  environment:
    - TZ=Europe/Moscow
    - PGTZ=Europe/Moscow
    - TIMEZONE=Europe/Moscow
    - DEBUG=false

    - DB_USER=school_user
    - DB_PASS=9BF2BFFC-7512-4379-924C-CA791033B389
    - DB_NAME=public
#    - DB_TEMPLATE=
#
#    - DB_EXTENSION=
#
#    - REPLICATION_MODE=
#    - REPLICATION_USER=
#    - REPLICATION_PASS=
#    - REPLICATION_SSLMODE=
  volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
